spring.application.name=MVCRestAPI
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/amit/downloads/MVCDB
spring.datasource.username=amit
spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update